### PR TITLE
Fix broken build

### PR DESCRIPTION
**Pull request by henryiii**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

The current build was never pushed. Going to rerender (the lazy way at first, unless the bot is down).

### CODE REVIEW

**Comment by henryiii** [comment]
@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
Actually the problem here is it's a no arch package, being built on Python 3.8; but it does not support 3.8 (as Tensorflow does not support 3.8). Also the Conda-forge support for TensorFlow is quite poor currently; hopefully it will improve with the new(ish) support for GPU + CPU packaging (though I think PyTorch is planned first).

**Comment by henryiii** [comment]
@chrisburr Any idea how to setup a no arch package that doesn't support Python 3.8?

**Comment by henryiii** [comment]
Dropped 3.8 from the run requirements too, since setup.py doesn't support it.

@conda-forge-admin, please rerender

**Comment by henryiii** [comment]
@mayou36 I think this is ready.

**Comment by mayou36** [comment]
Gee, I forgot to update _this_ requirements. Thanks for spotting!

**Pull request merged**
